support multiple devices
- [x] darwin + linux as different flakes
- [x] detect host type in Makefile for default device

diff --git a/install_home_manager b/install_home_manager
--- a/install_home_manager
+++ b/install_home_manager
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+DEVICE_SWITCH=$1
+DEVICE=$2
+
 # ===================================================================
 # nix/home-manager - https://github.com/nix-community/home-manager
 # ===================================================================
@@ -19,10 +22,31 @@ install_home_manager()
   fi
 }
 
+check_device()
+{
+  # check that a supported device is given as an argument
+  SUPPORTED_DEVICE_KAWASAKI="kawasaki"
+  SUPPORTED_DEVICE_MECHANICAL_ORCHARD_M2_MACBOOK="mechanical-orchard-m2-macbook"
+  SUPPORTED_DEVICES="$SUPPORTED_DEVICE_KAWASAKI $SUPPORTED_DEVICE_MECHANICAL_ORCHARD_M2_MACBOOK"
+  echo "supported devices=$SUPPORTED_DEVICES"
+
+  if [ $DEVICE_SWITCH != "--device" ] || [ -z $DEVICE ]; then
+    echo "--device <device_name> is required"
+    exit 1
+  fi
+
+  if [ $DEVICE = $SUPPORTED_DEVICE_KAWASAKI ] || [ $DEVICE = $SUPPORTED_DEVICE_MECHANICAL_ORCHARD_M2_MACBOOK ]; then
+    echo "supported device=$DEVICE"
+  else
+    echo "unsupported device=$DEVICE"
+    exit 1
+  fi
+}
+
 switch_home()
 {
   # download the latest rupurt/nix-home if we don't have it
-  if [ ! -e 'home.nix' ]; then
+  if [ ! -e 'install_home_manager' ]; then
     NIX_HOME_ARCHIVE_URL=https://github.com/rupurt/nix-home/archive/refs/heads/main.zip
     echo "fetching nix-home from $NIX_HOME_ARCHIVE_URL"
 
@@ -31,13 +55,15 @@ switch_home()
     cd /tmp/nix-home-main
   fi
 
-  nix build .
+  # build and switch to the flake of the given device
+  cd devices/${DEVICE}
   home-manager switch --flake .
 }
 
 # ensure nix is installed and activated in the current shell
 if [ -x "$(command -v nix --version)" ]; then
   install_home_manager
+  check_device
   switch_home
 else
   echo "nix is not installed or activated in the current shell"
